version: '3'

services:
  container1:
    image: sneh212/jbtf:latest
    ports:
      - "80:3000"
    networks:
      - mynetwork

  container2:
    image: sneh212/jbtb:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
