# Use the official Node.js 14 image as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

CMD ["npx", "prisma", "db", "push"]

CMD ["npx", "prisma", "generate"]

# Expose a port (if your application needs it)
EXPOSE 8080

# Start the application
CMD [ "node", "server.js" ]